# Generated by Django 3.1.1 on 2020-09-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fornecedor',
            old_name='nomeFantasia',
            new_name='nome_fantasia',
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
